version: "3.9"
services:
  nginx:
    image: nginx:alpine
    container_name: thetaone_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certs:/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:14
    container_name: thetaone_postgres
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=thetaone
      - DB_NAMESPACE=auth

  gotrue:
    image: esinx/gotrue:kakao
    container_name: thetaone_gotrue
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9999:9999"
    env_file: .env
    environment:
      - "GOTRUE_MAILER_AUTOCONFIRM=true"
    extra_hosts:
      - "host.docker.internal:host-gateway"
